import Foundation
import HarnessKit
import JavaScriptCore
import os

/// Syntax highlighting with the RN app's Shiki setup (mobile/src/lib/highlight.ts) running in
/// JavaScriptCore, so code is colored exactly as on the desktop, the phone and the Git tab.
///
/// One `JSContext` lives on the actor's own serial queue, so highlighting never runs on the main
/// thread and jobs run one at a time, the way the RN app's `serial` queue runs them. The script
/// (generated by ios/Tools/build-highlighter.ts) loads on the first job, not at init.
///
/// - Results are memoized in `cache` (200 entries, LRU). `cached(…)` reads it synchronously.
/// - Blocks over `maxChars` stay plain (nil), as do unbundled languages and unknown themes.
/// - A job whose task was cancelled before its turn came is skipped (throws CancellationError), so a
///   streaming block that changed again, or a view that went away, doesn't hold up the queue.
/// - Shiki stops tokenizing a line after 5 s (TOKENIZE_MS); the rest of that line stays plain. A
///   job that has started can't be interrupted: JavaScriptCore's public API has no watchdog.
/// - A script that fails to load or a job that throws resolves nil (plain), like highlightCached.
public actor Highlighter {
    /// MAX_HIGHLIGHT_CHARS: past this a block stays plain rather than hold the queue.
    public static let maxChars = 60_000

    public nonisolated let cache: HighlightCache
    private let loadScript: @Sendable () throws -> String
    private let queue = DispatchSerialQueue(label: "com.markhuot.harness.highlighter", qos: .userInitiated)
    private var engine: Engine?
    private var loadError: (any Error)?
    /// How long loading the script and the first job's JavaScript took, for diagnostics.
    public private(set) var timings = Timings()
    private static let log = Logger(subsystem: "com.markhuot.harness", category: "highlighter")

    public nonisolated var unownedExecutor: UnownedSerialExecutor { queue.asUnownedSerialExecutor() }

    /// `loadScript` returns the bundle's source; it runs once, on the highlighter's queue.
    public init(cacheSize: Int = 200, loadScript: @escaping @Sendable () throws -> String) {
        cache = HighlightCache(capacity: cacheSize)
        self.loadScript = loadScript
    }

    public init(scriptURL: URL, cacheSize: Int = 200) {
        self.init(cacheSize: cacheSize) { try String(contentsOf: scriptURL, encoding: .utf8) }
    }

    /// The highlighter for `highlighter.js` in `bundle` (the app's "Bundle highlighter" build phase puts it there).
    public static func bundled(in bundle: Bundle = .main) -> Highlighter {
        Highlighter(cacheSize: 200) {
            guard let url = bundle.url(forResource: "highlighter", withExtension: "js") else { throw HighlighterError.scriptMissing }
            return try String(contentsOf: url, encoding: .utf8)
        }
    }

    // MARK: - API

    /// Highlight `code` as `language` (a Shiki id, e.g. from codeLanguage/langForPath). Resolves nil
    /// when there's nothing to color it with: an unbundled language, an unknown theme, a block past
    /// `maxChars`, or a failure.
    public func highlight(_ code: String, language: String?, theme: String, appearance: ThemeAppearance) async throws -> Highlighted? {
        try run(code, language: language, theme: theme, diff: false, appearance: appearance)
    }

    /// Highlight a unified diff: each file's code is colored by its path's language (or `language`,
    /// a fence's, when the diff names no paths), each side tokenized as a whole file, and every line
    /// carries its kind. Lines of a diff come back even when no language is known.
    public func highlightDiff(_ code: String, language: String?, theme: String, appearance: ThemeAppearance) async throws -> Highlighted? {
        try run(code, language: language, theme: theme, diff: true, appearance: appearance)
    }

    /// The finished result for these inputs, if cached: `.some(nil)` when it's cached as plain.
    public nonisolated func cached(_ code: String, language: String?, theme: String, diff: Bool) -> Highlighted?? {
        cache.get(HighlightCache.Key(code: code, language: language, theme: theme, diff: diff))
    }

    /// The bundled Shiki language ids, in highlight.ts order.
    public func languages() throws -> [String] {
        try engineOrThrow().strings("languages")
    }

    /// The bundled Shiki theme names, in highlight.ts order.
    public func themes() throws -> [String] {
        try engineOrThrow().strings("themes")
    }

    /// Loads the script now (it otherwise loads on the first job), returning how long that took.
    @discardableResult
    public func warmUp() throws -> Duration {
        let clock = ContinuousClock()
        let start = clock.now
        _ = try engineOrThrow()
        return clock.now - start
    }

    public struct Timings: Sendable, Equatable {
        /// Evaluating the script into a fresh JSContext
        public var scriptLoad: Duration?
        /// The first job's highlight call (its language and theme load on first use), load excluded
        public var firstHighlight: Duration?

        public init(scriptLoad: Duration? = nil, firstHighlight: Duration? = nil) {
            self.scriptLoad = scriptLoad
            self.firstHighlight = firstHighlight
        }
    }

    // MARK: - Jobs

    private func run(_ code: String, language: String?, theme: String, diff: Bool, appearance: ThemeAppearance) throws -> Highlighted? {
        let key = HighlightCache.Key(code: code, language: language, theme: theme, diff: diff)
        if let hit = cache.get(key) { return hit }
        try Task.checkCancellation()
        // Measured in UTF-16 units, like JS's code.length.
        let result: Highlighted?
        if code.utf16.count > Self.maxChars {
            result = nil
        } else {
            do {
                let engine = try engineOrThrow()
                let start = ContinuousClock.now
                result = try engine.highlight(code, language, theme, diff, appearance)
                if timings.firstHighlight == nil { timings.firstHighlight = ContinuousClock.now - start }
            } catch {
                Self.log.error("highlight failed (\(language ?? "-", privacy: .public), \(theme, privacy: .public)): \(String(describing: error), privacy: .public)")
                result = nil
            }
        }
        cache.set(key, result)
        return result
    }

    private func engineOrThrow() throws -> Engine {
        if let engine { return engine }
        if let loadError { throw loadError }
        do {
            let start = ContinuousClock.now
            let e = try Engine(source: loadScript())
            timings.scriptLoad = ContinuousClock.now - start
            engine = e
            return e
        } catch {
            Self.log.error("highlighter script failed to load: \(String(describing: error), privacy: .public)")
            loadError = error
            throw error
        }
    }
}

public enum HighlighterError: Error, Equatable, CustomStringConvertible {
    case scriptMissing
    case script(String)
    case noResult

    public var description: String {
        switch self {
        case .scriptMissing: "highlighter.js isn't in the bundle (the Bundle highlighter build phase writes it)"
        case let .script(m): "highlighter script error: \(m)"
        case .noResult: "highlighter returned no result"
        }
    }
}

/// The JSContext and the bundle's `HarnessHighlighter` global. Only touched on the actor's queue.
private final class Engine {
    let context: JSContext
    let api: JSValue
    private var exception: String?

    /// JavaScriptCore's regex JIT mis-matches some of the patterns Shiki's JS engine generates (a
    /// trailing `// comment` in Swift or TypeScript comes out as an operator and identifiers); its
    /// regex interpreter matches Oniguruma. Apps on a device get no JIT, but the simulator and the
    /// Mac do, so the interpreter is asked for everywhere. JSC reads its options from the
    /// environment once, when the process's first VM starts, so this runs before the first
    /// JSContext; an explicit JSC_useRegExpJIT in the environment wins. It's faster here too: the
    /// grammars' regexes run a few times each, which never pays back JIT compilation.
    static let regExpInterpreter: Void = {
        setenv("JSC_useRegExpJIT", "false", 0)
    }()

    init(source: String) throws {
        _ = Self.regExpInterpreter
        guard let context = JSContext() else { throw HighlighterError.script("no JSContext") }
        context.name = "Harness highlighter"
        self.context = context
        var thrown: String?
        context.exceptionHandler = { _, value in thrown = value?.toString() ?? "unknown exception" }
        context.evaluateScript(source, withSourceURL: URL(string: "harness://highlighter.js"))
        if let thrown { throw HighlighterError.script(thrown) }
        guard let api = context.objectForKeyedSubscript("HarnessHighlighter"), api.isObject else {
            throw HighlighterError.script("HarnessHighlighter isn't defined")
        }
        self.api = api
        context.exceptionHandler = { [weak self] _, value in self?.exception = value?.toString() ?? "unknown exception" }
    }

    func strings(_ name: String) throws -> [String] {
        guard let list = api.objectForKeyedSubscript(name)?.toArray() as? [String] else { throw HighlighterError.script("\(name) isn't a string list") }
        return list
    }

    func highlight(_ code: String, _ lang: String?, _ theme: String, _ diff: Bool, _ appearance: ThemeAppearance) throws -> Highlighted? {
        var json: String?
        var failure: String?
        var called = false
        let done: @convention(block) (JSValue, JSValue) -> Void = { j, e in
            called = true
            if !j.isNull, !j.isUndefined { json = j.toString() }
            if !e.isNull, !e.isUndefined { failure = e.toString() }
        }
        exception = nil
        // The work resolves on promise jobs, which JavaScriptCore drains before the call returns.
        api.invokeMethod("highlight", withArguments: [code, lang ?? NSNull(), theme, diff, appearance.rawValue, unsafeBitCast(done, to: AnyObject.self)])
        if let exception { throw HighlighterError.script(exception) }
        if let failure { throw HighlighterError.script(failure) }
        guard called, let json else { throw HighlighterError.noResult }
        return try JSONDecoder().decode(Highlighted?.self, from: Data(json.utf8))
    }
}
